ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*
AVR_TOOLS_DIR = /usr
BOARDS_TXT = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
ARDUINO_LIB_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/libraries
ARCHITECTURE = archlinux-arduino
USER_LIB_PATH = .

BOARD_TAG = mega


include /home/roadrage/Arduino-Makefile/Arduino.mk
